version: '3.4'
name: 'keeperdata.bridge'
services:
  localstack:
    container_name: "localstack-emulator"
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sns,firehose
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:4566/health']
      interval: 5s
      start_period: 5s
      retries: 5
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  keeperdata.bridge:
    platform: linux
    build: ./
    ports:
      - '8080:8080'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 8080
      LOCALSTACK_ENDPOINT: http://localstack-emulator:4566
      MONGO_URI: mongodb://mongodb:27017/
      ASPNETCORE_HTTP_PORTS: 8080
      LocalStack_ServiceURL: http://localstack-emulator:4566
      IMB_S3_ACCESS_KEY: test
      IMB_S3_ACCESS_SECRET: test
      StorageConfiguration__ExternalStorage__BucketName: test-external-bucket
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
