name: 'keeperdata_bridge'
services:
  localstack:
    container_name: "kdb-localstack-emulator"
    image: localstack/localstack:3.0.2
    ports:
      - "4567:4566"
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sns,firehose
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'http://kdb-localstack-emulator:4566/health']
      interval: 5s
      start_period: 5s
      retries: 5
    networks:
      - cdp-tenant

  redis:
    container_name: "kdb-redis"
    image: redis:7.2.3-alpine3.18
    ports:
      - '6380:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    container_name: kdbridge_mongodb
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27018:27017'
    volumes:
      - mongodb-data:/data
    restart: always
  
  keeperdata_bridge:
    container_name: "keeperdata_bridge"
    platform: linux
    image: keeperdata_bridge
    build: ./
    ports:
      - '5560:5560'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 5560
      LOCALSTACK_ENDPOINT: http://kdb-localstack-emulator:4566
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    name: cdp-tenant
